[package]
name = "task_9"
version = "0.1.0"
edition = "2021"




[dependencies]
reqwest = "0.12.7"
scraper = "0.20.0"

[dependencies.clap]
version = "4.5.17"
features = ["derive"]


[dependencies.tokio]
version="1.40.0"
features=["full"]